package com.app.oniontray.CountrySpinner;

import java.util.ArrayList;
import java.util.TreeSet;

/**
 * Created by nextbrain on 18/4/17.
 */

public class CountryCodes {


    protected static final TreeSet<String> CANADA_CODES = new TreeSet<String>();
    protected static final TreeSet<String> US_CODES = new TreeSet<String>();
    protected static final TreeSet<String> DO_CODES = new TreeSet<String>();
    protected static final TreeSet<String> PR_CODES = new TreeSet<String>();

    static {
        //USA
        US_CODES.add("201");
        US_CODES.add("202");
        US_CODES.add("203");
        US_CODES.add("205");
        US_CODES.add("206");
        US_CODES.add("207");
        US_CODES.add("208");
        US_CODES.add("209");
        US_CODES.add("210");
        US_CODES.add("212");
        US_CODES.add("213");
        US_CODES.add("214");
        US_CODES.add("215");
        US_CODES.add("216");
        US_CODES.add("217");
        US_CODES.add("218");
        US_CODES.add("219");
        US_CODES.add("224");
        US_CODES.add("225");
        US_CODES.add("228");
        US_CODES.add("229");
        US_CODES.add("231");
        US_CODES.add("234");
        US_CODES.add("239");
        US_CODES.add("240");
        US_CODES.add("248");
        US_CODES.add("251");
        US_CODES.add("252");
        US_CODES.add("253");
        US_CODES.add("254");
        US_CODES.add("256");
        US_CODES.add("260");
        US_CODES.add("262");
        US_CODES.add("267");
        US_CODES.add("269");
        US_CODES.add("270");
        US_CODES.add("276");
        US_CODES.add("281");
        US_CODES.add("301");
        US_CODES.add("302");
        US_CODES.add("303");
        US_CODES.add("304");
        US_CODES.add("305");
        US_CODES.add("307");
        US_CODES.add("308");
        US_CODES.add("309");
        US_CODES.add("310");
        US_CODES.add("312");
        US_CODES.add("313");
        US_CODES.add("314");
        US_CODES.add("315");
        US_CODES.add("316");
        US_CODES.add("317");
        US_CODES.add("318");
        US_CODES.add("319");
        US_CODES.add("320");
        US_CODES.add("321");
        US_CODES.add("323");
        US_CODES.add("325");
        US_CODES.add("330");
        US_CODES.add("334");
        US_CODES.add("336");
        US_CODES.add("337");
        US_CODES.add("339");
        US_CODES.add("347");
        US_CODES.add("351");
        US_CODES.add("352");
        US_CODES.add("360");
        US_CODES.add("361");
        US_CODES.add("386");
        US_CODES.add("401");
        US_CODES.add("402");
        US_CODES.add("404");
        US_CODES.add("405");
        US_CODES.add("406");
        US_CODES.add("407");
        US_CODES.add("408");
        US_CODES.add("409");
        US_CODES.add("410");
        US_CODES.add("412");
        US_CODES.add("413");
        US_CODES.add("414");
        US_CODES.add("415");
        US_CODES.add("417");
        US_CODES.add("419");
        US_CODES.add("423");
        US_CODES.add("425");
        US_CODES.add("430");
        US_CODES.add("432");
        US_CODES.add("434");
        US_CODES.add("435");
        US_CODES.add("440");
        US_CODES.add("443");
        US_CODES.add("469");
        US_CODES.add("478");
        US_CODES.add("479");
        US_CODES.add("480");
        US_CODES.add("484");
        US_CODES.add("501");
        US_CODES.add("502");
        US_CODES.add("503");
        US_CODES.add("504");
        US_CODES.add("505");
        US_CODES.add("507");
        US_CODES.add("508");
        US_CODES.add("509");
        US_CODES.add("510");
        US_CODES.add("512");
        US_CODES.add("513");
        US_CODES.add("515");
        US_CODES.add("516");
        US_CODES.add("517");
        US_CODES.add("518");
        US_CODES.add("520");
        US_CODES.add("530");
        US_CODES.add("540");
        US_CODES.add("541");
        US_CODES.add("551");
        US_CODES.add("559");
        US_CODES.add("561");
        US_CODES.add("562");
        US_CODES.add("563");
        US_CODES.add("567");
        US_CODES.add("570");
        US_CODES.add("571");
        US_CODES.add("573");
        US_CODES.add("574");
        US_CODES.add("575");
        US_CODES.add("580");
        US_CODES.add("585");
        US_CODES.add("586");
        US_CODES.add("601");
        US_CODES.add("602");
        US_CODES.add("603");
        US_CODES.add("605");
        US_CODES.add("606");
        US_CODES.add("607");
        US_CODES.add("608");
        US_CODES.add("609");
        US_CODES.add("610");
        US_CODES.add("612");
        US_CODES.add("614");
        US_CODES.add("615");
        US_CODES.add("616");
        US_CODES.add("617");
        US_CODES.add("618");
        US_CODES.add("619");
        US_CODES.add("620");
        US_CODES.add("623");
        US_CODES.add("626");
        US_CODES.add("630");
        US_CODES.add("631");
        US_CODES.add("636");
        US_CODES.add("641");
        US_CODES.add("646");
        US_CODES.add("650");
        US_CODES.add("651");
        US_CODES.add("660");
        US_CODES.add("661");
        US_CODES.add("662");
        US_CODES.add("678");
        US_CODES.add("682");
        US_CODES.add("701");
        US_CODES.add("702");
        US_CODES.add("703");
        US_CODES.add("704");
        US_CODES.add("706");
        US_CODES.add("707");
        US_CODES.add("708");
        US_CODES.add("712");
        US_CODES.add("713");
        US_CODES.add("714");
        US_CODES.add("715");
        US_CODES.add("716");
        US_CODES.add("717");
        US_CODES.add("718");
        US_CODES.add("719");
        US_CODES.add("720");
        US_CODES.add("724");
        US_CODES.add("727");
        US_CODES.add("731");
        US_CODES.add("732");
        US_CODES.add("734");
        US_CODES.add("740");
        US_CODES.add("754");
        US_CODES.add("757");
        US_CODES.add("760");
        US_CODES.add("763");
        US_CODES.add("765");
        US_CODES.add("770");
        US_CODES.add("772");
        US_CODES.add("773");
        US_CODES.add("774");
        US_CODES.add("775");
        US_CODES.add("781");
        US_CODES.add("785");
        US_CODES.add("786");
        US_CODES.add("801");
        US_CODES.add("802");
        US_CODES.add("803");
        US_CODES.add("804");
        US_CODES.add("805");
        US_CODES.add("806");
        US_CODES.add("808");
        US_CODES.add("810");
        US_CODES.add("812");
        US_CODES.add("813");
        US_CODES.add("814");
        US_CODES.add("815");
        US_CODES.add("816");
        US_CODES.add("817");
        US_CODES.add("818");
        US_CODES.add("828");
        US_CODES.add("830");
        US_CODES.add("831");
        US_CODES.add("832");
        US_CODES.add("843");
        US_CODES.add("845");
        US_CODES.add("847");
        US_CODES.add("848");
        US_CODES.add("850");
        US_CODES.add("856");
        US_CODES.add("857");
        US_CODES.add("858");
        US_CODES.add("859");
        US_CODES.add("860");
        US_CODES.add("862");
        US_CODES.add("863");
        US_CODES.add("864");
        US_CODES.add("865");
        US_CODES.add("866");
        US_CODES.add("870");
        US_CODES.add("901");
        US_CODES.add("903");
        US_CODES.add("904");
        US_CODES.add("906");
        US_CODES.add("907");
        US_CODES.add("908");
        US_CODES.add("909");
        US_CODES.add("910");
        US_CODES.add("912");
        US_CODES.add("913");
        US_CODES.add("914");
        US_CODES.add("915");
        US_CODES.add("916");
        US_CODES.add("917");
        US_CODES.add("918");
        US_CODES.add("919");
        US_CODES.add("920");
        US_CODES.add("925");
        US_CODES.add("928");
        US_CODES.add("931");
        US_CODES.add("936");
        US_CODES.add("937");
        US_CODES.add("940");
        US_CODES.add("941");
        US_CODES.add("947");
        US_CODES.add("949");
        US_CODES.add("951");
        US_CODES.add("952");
        US_CODES.add("954");
        US_CODES.add("956");
        US_CODES.add("970");
        US_CODES.add("971");
        US_CODES.add("972");
        US_CODES.add("973");
        US_CODES.add("978");
        US_CODES.add("979");
        US_CODES.add("980");
        US_CODES.add("985");
        US_CODES.add("989");

        //Dominican Republic
        DO_CODES.add("809");
        DO_CODES.add("829");
        DO_CODES.add("849");

        //Puerto Rico
        PR_CODES.add("787");
        PR_CODES.add("939");

        //Canada
        CANADA_CODES.add("204");
        CANADA_CODES.add("226");
        CANADA_CODES.add("236");
        CANADA_CODES.add("249");
        CANADA_CODES.add("250");
        CANADA_CODES.add("289");
        CANADA_CODES.add("306");
        CANADA_CODES.add("343");
        CANADA_CODES.add("365");
        CANADA_CODES.add("387");
        CANADA_CODES.add("403");
        CANADA_CODES.add("416");
        CANADA_CODES.add("418");
        CANADA_CODES.add("431");
        CANADA_CODES.add("437");
        CANADA_CODES.add("438");
        CANADA_CODES.add("450");
        CANADA_CODES.add("506");
        CANADA_CODES.add("514");
        CANADA_CODES.add("519");
        CANADA_CODES.add("548");
        CANADA_CODES.add("579");
        CANADA_CODES.add("581");
        CANADA_CODES.add("587");
        CANADA_CODES.add("604");
        CANADA_CODES.add("613");
        CANADA_CODES.add("639");
        CANADA_CODES.add("647");
        CANADA_CODES.add("672");
        CANADA_CODES.add("705");
        CANADA_CODES.add("709");
        CANADA_CODES.add("742");
        CANADA_CODES.add("778");
        CANADA_CODES.add("780");
        CANADA_CODES.add("782");
        CANADA_CODES.add("807");
        CANADA_CODES.add("819");
        CANADA_CODES.add("825");
        CANADA_CODES.add("867");
        CANADA_CODES.add("873");
        CANADA_CODES.add("902");
        CANADA_CODES.add("905");
    }


    public TreeSet<String> getCanadaCodes(){
        return CANADA_CODES;
    }


    public TreeSet<String> getUsCodes(){
        return US_CODES;
    }

    public TreeSet<String> getDoCodes(){
        return DO_CODES;
    }

    public TreeSet<String> getPrCodes(){
        return PR_CODES;
    }



    protected static final ArrayList<String> ARABIC_COUNTRY_NAME = new ArrayList<String>();


    static {

        ARABIC_COUNTRY_NAME.add("أفغانستان");
        ARABIC_COUNTRY_NAME.add("ألبانيا");
        ARABIC_COUNTRY_NAME.add("الجزائر");
        ARABIC_COUNTRY_NAME.add("ساموا الأمريكية");
        ARABIC_COUNTRY_NAME.add("أندورا");
        ARABIC_COUNTRY_NAME.add("أنغولا");
        ARABIC_COUNTRY_NAME.add("أنغيلا");
        ARABIC_COUNTRY_NAME.add("أنتيغوا وبربودا");
        ARABIC_COUNTRY_NAME.add("الأرجنتين");
        ARABIC_COUNTRY_NAME.add("أرمينيا");
        ARABIC_COUNTRY_NAME.add("أروبا");
        ARABIC_COUNTRY_NAME.add("أستراليا");
        ARABIC_COUNTRY_NAME.add("النمسا");
        ARABIC_COUNTRY_NAME.add("أذربيجان");
        ARABIC_COUNTRY_NAME.add("جزر الباهاما");
        ARABIC_COUNTRY_NAME.add("البحرين");
        ARABIC_COUNTRY_NAME.add("بنغلاديش");
        ARABIC_COUNTRY_NAME.add("بربادوس");
        ARABIC_COUNTRY_NAME.add("روسيا البيضاء");
        ARABIC_COUNTRY_NAME.add("بلجيكا");
        ARABIC_COUNTRY_NAME.add("بليز");
        ARABIC_COUNTRY_NAME.add("بنين");
        ARABIC_COUNTRY_NAME.add("برمودا");
        ARABIC_COUNTRY_NAME.add("بوتان");
        ARABIC_COUNTRY_NAME.add("بوليفيا");
        ARABIC_COUNTRY_NAME.add("البوسنة والهرسك");
        ARABIC_COUNTRY_NAME.add("بوتسوانا");
        ARABIC_COUNTRY_NAME.add("البرازيل");
        ARABIC_COUNTRY_NAME.add("إقليم المحيط الهندي البريطاني");
        ARABIC_COUNTRY_NAME.add("جزر فيرجن البريطانية");
        ARABIC_COUNTRY_NAME.add("بروناي");
        ARABIC_COUNTRY_NAME.add("بلغاريا");
        ARABIC_COUNTRY_NAME.add("بوركينا فاسو");
        ARABIC_COUNTRY_NAME.add("بوروندي");
        ARABIC_COUNTRY_NAME.add("كمبوديا");
        ARABIC_COUNTRY_NAME.add("الكاميرون");
        ARABIC_COUNTRY_NAME.add("كندا");
        ARABIC_COUNTRY_NAME.add("الرأس الأخضر");
        ARABIC_COUNTRY_NAME.add("منطقة البحر الكاريبي هولندا");
        ARABIC_COUNTRY_NAME.add("جزر كايمان");
        ARABIC_COUNTRY_NAME.add("جمهورية أفريقيا الوسطى");
        ARABIC_COUNTRY_NAME.add("تشاد");
        ARABIC_COUNTRY_NAME.add("شيلي");
        ARABIC_COUNTRY_NAME.add("الصين");
        ARABIC_COUNTRY_NAME.add("كولومبيا");
        ARABIC_COUNTRY_NAME.add("جزر القمر");
        ARABIC_COUNTRY_NAME.add("الكونغو (جمهورية الكونغو الديمقراطية)");
        ARABIC_COUNTRY_NAME.add("الكونغو (جمهورية)");
        ARABIC_COUNTRY_NAME.add("جزر كوك");
        ARABIC_COUNTRY_NAME.add("كوستاريكا");
        ARABIC_COUNTRY_NAME.add("كوت ديفوار");
        ARABIC_COUNTRY_NAME.add("كرواتيا");
        ARABIC_COUNTRY_NAME.add("كوبا");
        ARABIC_COUNTRY_NAME.add("كوراساو");
        ARABIC_COUNTRY_NAME.add("قبرص");
        ARABIC_COUNTRY_NAME.add("جمهورية التشيك");
        ARABIC_COUNTRY_NAME.add("الدنمارك");
        ARABIC_COUNTRY_NAME.add("جيبوتي");
        ARABIC_COUNTRY_NAME.add("دومينيكا");
        ARABIC_COUNTRY_NAME.add("جمهورية الدومينيكان");
        ARABIC_COUNTRY_NAME.add("الإكوادور");
        ARABIC_COUNTRY_NAME.add("مصر");
        ARABIC_COUNTRY_NAME.add("السلفادور");
        ARABIC_COUNTRY_NAME.add("غينيا الاستوائية");
        ARABIC_COUNTRY_NAME.add("إريتريا");
        ARABIC_COUNTRY_NAME.add("استونيا");
        ARABIC_COUNTRY_NAME.add("إثيوبيا");
        ARABIC_COUNTRY_NAME.add("جزر فوكلاند");
        ARABIC_COUNTRY_NAME.add("جزر فارو");
        ARABIC_COUNTRY_NAME.add("فيجي");
        ARABIC_COUNTRY_NAME.add("فنلندا");
        ARABIC_COUNTRY_NAME.add("فرنسا");
        ARABIC_COUNTRY_NAME.add("جويانا الفرنسية");
        ARABIC_COUNTRY_NAME.add("بولينيزيا الفرنسية");
        ARABIC_COUNTRY_NAME.add("الغابون");
        ARABIC_COUNTRY_NAME.add("غامبيا");
        ARABIC_COUNTRY_NAME.add("جورجيا");
        ARABIC_COUNTRY_NAME.add("ألمانيا");
        ARABIC_COUNTRY_NAME.add("غانا");
        ARABIC_COUNTRY_NAME.add("جبل طارق");
        ARABIC_COUNTRY_NAME.add("اليونان");
        ARABIC_COUNTRY_NAME.add("غرينلاند");
        ARABIC_COUNTRY_NAME.add("وغرينادا");
        ARABIC_COUNTRY_NAME.add("غوادلوب");
        ARABIC_COUNTRY_NAME.add("غوام");
        ARABIC_COUNTRY_NAME.add("غواتيمالا");
        ARABIC_COUNTRY_NAME.add("غينيا");
        ARABIC_COUNTRY_NAME.add("غينيا بيساو");
        ARABIC_COUNTRY_NAME.add("غيانا");
        ARABIC_COUNTRY_NAME.add("هايتي");
        ARABIC_COUNTRY_NAME.add("هندوراس");
        ARABIC_COUNTRY_NAME.add("المجر");
        ARABIC_COUNTRY_NAME.add("أيسلندا");
        ARABIC_COUNTRY_NAME.add("الهند");
        ARABIC_COUNTRY_NAME.add("اندونيسيا");
        ARABIC_COUNTRY_NAME.add("إيران");
        ARABIC_COUNTRY_NAME.add("العراق");
        ARABIC_COUNTRY_NAME.add("ايرلندا");
        ARABIC_COUNTRY_NAME.add("إسرائيل");
        ARABIC_COUNTRY_NAME.add("إيطاليا");
        ARABIC_COUNTRY_NAME.add("جامايكا");
        ARABIC_COUNTRY_NAME.add("اليابان");
        ARABIC_COUNTRY_NAME.add("الأردن");
        ARABIC_COUNTRY_NAME.add("كازاخستان");
        ARABIC_COUNTRY_NAME.add("كينيا");
        ARABIC_COUNTRY_NAME.add("كيريباتي");
        ARABIC_COUNTRY_NAME.add("الكويت");
        ARABIC_COUNTRY_NAME.add("قيرغيزستان");
        ARABIC_COUNTRY_NAME.add("لاوس");
        ARABIC_COUNTRY_NAME.add("لاتفيا");
        ARABIC_COUNTRY_NAME.add("لبنان");
        ARABIC_COUNTRY_NAME.add("ليسوتو");
        ARABIC_COUNTRY_NAME.add("ليبيريا");
        ARABIC_COUNTRY_NAME.add("ليبيا");
        ARABIC_COUNTRY_NAME.add("ليختنشتاين");
        ARABIC_COUNTRY_NAME.add("ليتوانيا");
        ARABIC_COUNTRY_NAME.add("لوكسمبورغ");
        ARABIC_COUNTRY_NAME.add("ماكاو");
        ARABIC_COUNTRY_NAME.add("مقدونيا");
        ARABIC_COUNTRY_NAME.add("مدغشقر");
        ARABIC_COUNTRY_NAME.add("ملاوي");
        ARABIC_COUNTRY_NAME.add("ماليزيا");
        ARABIC_COUNTRY_NAME.add("جزر المالديف");
        ARABIC_COUNTRY_NAME.add("مالي");
        ARABIC_COUNTRY_NAME.add("مالطا");
        ARABIC_COUNTRY_NAME.add("جزر مارشال");
        ARABIC_COUNTRY_NAME.add("المارتينيك");
        ARABIC_COUNTRY_NAME.add("موريتانيا");
        ARABIC_COUNTRY_NAME.add("موريشيوس");
        ARABIC_COUNTRY_NAME.add("المكسيك");
        ARABIC_COUNTRY_NAME.add("ميكرونيزيا");
        ARABIC_COUNTRY_NAME.add("مولدوفا");
        ARABIC_COUNTRY_NAME.add("موناكو");
        ARABIC_COUNTRY_NAME.add("منغوليا");
        ARABIC_COUNTRY_NAME.add("الجبل الأسود");
        ARABIC_COUNTRY_NAME.add("ومونتسيرات");
        ARABIC_COUNTRY_NAME.add("المغرب");
        ARABIC_COUNTRY_NAME.add("موزامبيق");
        ARABIC_COUNTRY_NAME.add("ميانمار");
        ARABIC_COUNTRY_NAME.add("ناميبيا");
        ARABIC_COUNTRY_NAME.add("ناورو");
        ARABIC_COUNTRY_NAME.add("نيبال");
        ARABIC_COUNTRY_NAME.add("هولندا");
        ARABIC_COUNTRY_NAME.add("كاليدونيا الجديدة");
        ARABIC_COUNTRY_NAME.add("نيوزيلندا");
        ARABIC_COUNTRY_NAME.add("نيكاراغوا");
        ARABIC_COUNTRY_NAME.add("النيجر");
        ARABIC_COUNTRY_NAME.add("نيجيريا");
        ARABIC_COUNTRY_NAME.add("نيوي");
        ARABIC_COUNTRY_NAME.add("جزيرة نورفولك");
        ARABIC_COUNTRY_NAME.add("كوريا الشمالية");
        ARABIC_COUNTRY_NAME.add("جزر ماريانا الشمالية");
        ARABIC_COUNTRY_NAME.add("النرويج");
        ARABIC_COUNTRY_NAME.add("عمان");
        ARABIC_COUNTRY_NAME.add("باكستان");
        ARABIC_COUNTRY_NAME.add("بالاو");
        ARABIC_COUNTRY_NAME.add("فلسطين");
        ARABIC_COUNTRY_NAME.add("بنما");
        ARABIC_COUNTRY_NAME.add("بابوا غينيا الجديدة");
        ARABIC_COUNTRY_NAME.add("باراغواي");
        ARABIC_COUNTRY_NAME.add("بيرو");
        ARABIC_COUNTRY_NAME.add("الفلبين");
        ARABIC_COUNTRY_NAME.add("بولندا");
        ARABIC_COUNTRY_NAME.add("البرتغال");
        ARABIC_COUNTRY_NAME.add("بورتوريكو");
        ARABIC_COUNTRY_NAME.add("قطر");
        ARABIC_COUNTRY_NAME.add("ريونيون");
        ARABIC_COUNTRY_NAME.add("رومانيا");
        ARABIC_COUNTRY_NAME.add("روسيا");
        ARABIC_COUNTRY_NAME.add("رواندا");
        ARABIC_COUNTRY_NAME.add("سانت بارتيليمي");
        ARABIC_COUNTRY_NAME.add("سانت هيلانة");
        ARABIC_COUNTRY_NAME.add("سانت كيتس ونيفيس");
        ARABIC_COUNTRY_NAME.add("سانت لوسيا");
        ARABIC_COUNTRY_NAME.add("سانت مارتن");
        ARABIC_COUNTRY_NAME.add("سان بيار وميكلون");
        ARABIC_COUNTRY_NAME.add("سانت فنسنت وجزر غرينادين");
        ARABIC_COUNTRY_NAME.add("ساموا");
        ARABIC_COUNTRY_NAME.add("سان مارينو");
        ARABIC_COUNTRY_NAME.add("ساو تومي وبرينسيبي");
        ARABIC_COUNTRY_NAME.add("المملكة العربية السعودية");
        ARABIC_COUNTRY_NAME.add("السنغال");
        ARABIC_COUNTRY_NAME.add("صربيا");
        ARABIC_COUNTRY_NAME.add("سيشيل");
        ARABIC_COUNTRY_NAME.add("سيراليون");
        ARABIC_COUNTRY_NAME.add("سنغافورة");
        ARABIC_COUNTRY_NAME.add("سانت مارتن");
        ARABIC_COUNTRY_NAME.add("سلوفاكيا");
        ARABIC_COUNTRY_NAME.add("سلوفينيا");
        ARABIC_COUNTRY_NAME.add("جزر سليمان");
        ARABIC_COUNTRY_NAME.add("الصومال");
        ARABIC_COUNTRY_NAME.add("جنوب أفريقيا");
        ARABIC_COUNTRY_NAME.add("كوريا الجنوبية");
        ARABIC_COUNTRY_NAME.add("جنوب السودان");
        ARABIC_COUNTRY_NAME.add("اسبانيا");
        ARABIC_COUNTRY_NAME.add("سري لانكا");
        ARABIC_COUNTRY_NAME.add("السودان");
        ARABIC_COUNTRY_NAME.add("سورينام");
        ARABIC_COUNTRY_NAME.add("سوازيلاند");
        ARABIC_COUNTRY_NAME.add("السويد");
        ARABIC_COUNTRY_NAME.add("سويسرا");
        ARABIC_COUNTRY_NAME.add("سوريا");
        ARABIC_COUNTRY_NAME.add("تايوان");
        ARABIC_COUNTRY_NAME.add("طاجيكستان");
        ARABIC_COUNTRY_NAME.add("تنزانيا");
        ARABIC_COUNTRY_NAME.add("تايلاند");
        ARABIC_COUNTRY_NAME.add("تيمور ليشتي");
        ARABIC_COUNTRY_NAME.add("توغو");
        ARABIC_COUNTRY_NAME.add("توكيلاو");
        ARABIC_COUNTRY_NAME.add("تونغا");
        ARABIC_COUNTRY_NAME.add("ترينيداد وتوباغو");
        ARABIC_COUNTRY_NAME.add("تونس");
        ARABIC_COUNTRY_NAME.add("تركيا");
        ARABIC_COUNTRY_NAME.add("تركمانستان");
        ARABIC_COUNTRY_NAME.add("جزر تركس وكايكوس");
        ARABIC_COUNTRY_NAME.add("توفالو");
        ARABIC_COUNTRY_NAME.add("جزر فيرجن الأمريكية");
        ARABIC_COUNTRY_NAME.add("أوغندا");
        ARABIC_COUNTRY_NAME.add("أوكرانيا");
        ARABIC_COUNTRY_NAME.add("الإمارات العربية المتحدة");
        ARABIC_COUNTRY_NAME.add("المملكة المتحدة");
        ARABIC_COUNTRY_NAME.add("الولايات المتحدة الأمريكية");
        ARABIC_COUNTRY_NAME.add("أوروغواي");
        ARABIC_COUNTRY_NAME.add("أوزبكستان");
        ARABIC_COUNTRY_NAME.add("فانواتو");
        ARABIC_COUNTRY_NAME.add("مدينة الفاتيكان");
        ARABIC_COUNTRY_NAME.add("فنزويلا");
        ARABIC_COUNTRY_NAME.add("فيتنام");
        ARABIC_COUNTRY_NAME.add("واليس وفوتونا");
        ARABIC_COUNTRY_NAME.add("اليمن");
        ARABIC_COUNTRY_NAME.add("زامبيا");
        ARABIC_COUNTRY_NAME.add("زيمبابوي");
        ARABIC_COUNTRY_NAME.add("سوريا");

    }


    public ArrayList<String> getArabicCountryNames(){
        return ARABIC_COUNTRY_NAME;
    }

    public String getArabicCountryName(int pos){
        return ARABIC_COUNTRY_NAME.get(pos);
    }



}
